version: "3.7"

services:
  dev_database:
    restart: unless-stopped
    image: postgres:16-alpine
    volumes:
      - dev_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"

  test_database:
    restart: unless-stopped
    image: postgres:16-alpine
    volumes:
      - test_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${TEST_POSTGRES_DB}
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "${TEST_POSTGRES_PORT}:5432"

volumes:
  dev_database_data:
  test_database_data:
