version: "3.7"

services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    depends_on:
      - postgres
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - 80:8000

volumes:
  postgres_data:
